### ISSUE TITLE
Toggle Properties twice without reload doesn't work

### ISSUE THREAD

**Issue by bgrolleman** [logseq/db-test#8] opened 2024-08-13 18:52 UTC
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I did a large import (old personal graph) to test it's performance and was looking at lists of properties. Found the toggle properties but when I tried to toggle back it didn't work. Found ways going to another page and back restores the functionality

### Reproduce the Bug

1. Go to a page with properties
2. Hit the menu -> toggle properties
3. Hit the menu -> toggle properties

### Expected Behavior

That toggle is a toggle and so I can use it multiple times without having to switch / reload pages

### Browser, Desktop or Mobile Platform Information

Windows 10, MS Edge

Logseq 0.10.10 (This should really have a build number)

### Additional Context

No errors in the console from what I could see, just inaction. 

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by RCmerci** [comment] 2024-08-14 10:39
I can't reproduce this bug, it might be related to specific data.
could you provide a test-graph? (export as SQLite DB)

**Comment by bgrolleman** [comment] 2024-08-14 19:29
This test data was an old graph of mine that might contain personal data. Bit busy with work but will see if I can simulate the issue with a smaller dataset and export that.

**Comment by tiensonqin** [comment] 2024-08-16 01:54
Thanks for the report! It's fixed now.

**Closed by tiensonqin** 2024-08-16 01:54 UTC
Labels: bug
