### ISSUE TITLE
Pressing MOD+p to add a page property causes a page scroll

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#37] opened 2024-08-22 09:45 UTC
Steps to reproduce:
- Open/create a page with enough content to enable scrolling
- Navigate to the top of the page while in command mode press MOD+p to add a page property
- Note in the background that the page automatically scrolls down

https://github.com/user-attachments/assets/ad85859a-825b-47fb-a916-3d3d6333d0ce

**Comment by tiensonqin** [comment] 2024-08-26 05:07
@Bad3r Can you reproduce this bug on https://test.logseq.com/? I wonder if it's caused by some shortcuts from plugins.

**Comment by Bad3r** [comment] 2024-08-26 05:53
> @Bad3r Can you reproduce this bug on [test.logseq.com](https://test.logseq.com/)? I wonder if it's caused by some shortcuts from plugins.

I can reproduce it on [test.logseq.com](https://test.logseq.com/)

I created a new graph with the same page here is the db note that GitHub doesn't allow sqlite file extension so I used gofile instead: 

https://gofile.io/d/ur0l1f

**Comment by tiensonqin** [comment] 2024-08-26 08:06
Unfortunately, I still can't reproduce this bug with the exported SQLite db. @xyhp915 Can you reproduce this bug?

**Comment by xyhp915** [comment] 2024-08-26 09:02
It can't be reproduced on the MacOS. However, the bug may be on Windows, and it is speculated that it is caused by the conflict of this shortcut key `ctrl + p`.
![CleanShot 2024-08-26 at 16 58 14@2x](https://github.com/user-attachments/assets/5388839f-f141-49b6-ab89-a5dbb751244a)

**Comment by xyhp915** [comment] 2024-08-26 09:29
@Bad3r @tiensonqin My initial idea is to modify it to `p a` to avoid conflicts, while maintaining consistency with other property-related shortcuts.
![CleanShot 2024-08-26 at 17 27 40@2x](https://github.com/user-attachments/assets/06fb43dd-6b71-40e3-8b5d-fb87d12eb90b)

**Comment by tiensonqin** [comment] 2024-09-04 03:49
I updated the shortcut to be `ctrl+alt+p` for Windows and Linux. 
I didn't change it to `p a` because it doesn't work in the editing mode, but we expect this command to be used a lot in the selection mode.
Initially, I wanted to use `alt+p` but noticed it's used for navigating PDF pages.
Let me know if you any suggestions on other shortcuts.

**Comment by tiensonqin** [comment] 2024-09-04 12:28
Closing this issue for now, but feel free to discuss further here.

**Closed by tiensonqin** 2024-09-04 12:28 UTC
Labels: bug, can reproduce, ui
