### ISSUE TITLE
Pasting text with formatted date

### ISSUE THREAD

**Issue by hdansou** [logseq/db-test#108] opened 2024-09-18 20:29 UTC
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When pasting a text with the formatted date [[2024-09-12]] in a node, it does not render.
What is the new way of adding formatted text into nodes?

### Reproduce the Bug

Using a text editor, create bullet points with some text containing formatted dates. Example:
```text
- This is an event that happened on [[2024-09-12]]
- I read this [[getting things done]] on the [[2024-09-12]]
- note sure if the #tag_name will show
deadline:: [[2024-09-10]]
```shell
history | grep demo
```
- This is an `inline code block`
- This is a macro {{JIRA 1234}}
-  > This is a quote  
- [Demo Link](https://logseq.com)
- ## Heading 2
- Some text
```

### Expected Behavior

The input dates should be converted to date references and should be visible in the UI.

### Screenshots

![image](https://github.com/user-attachments/assets/c3b1c388-89d9-446c-8fde-3add5cb3de3f)


### Browser, Desktop or Mobile Platform Information

_No response_

### Additional Context

_No response_

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment] 2024-09-18 20:35
Hi. I think this is a duplicate of https://github.com/logseq/db-test/issues/103. If so, you can close this and follow that issue

**Comment by tiensonqin** [comment] 2024-09-19 10:41
Closing this one in favor of #103.

**Closed by tiensonqin** 2024-09-19 10:41 UTC
Labels: duplicate, editor:copy-paste
